name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set AWS region (to prevent boto3 errors)
        run: |
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV

      - run: pip install '.[all]'
      - run: python -m pip install --upgrade pip
      - run: pip install pytest pytest-cov ruff
      - run: ruff check src tests examples
      - run: pytest --cov=src --cov-report=term-missing tests
